### ISSUE TITLE
Hardcoded paths to scripts prevent global installation

### ISSUE THREAD

**Issue by eburgueno** [enormandeau/mapcomp#6] opened 2018-02-07 21:36 UTC
Hi there, we wanted to deploy MapComp in our HPC cluster so that our users can run it, but I noticed that your scripts assume that `mapcomp` is being run from `pwd`. You should be able to add the mapcomp directory to your PATH and run it from an arbitrary location.

In fact, in most HPC environments, software is installed in a non-system tree and loaded into users' environments via GNU Modules or the like.

As they stand, the scripts are unusable for a multi-user environment.

**Comment by enormandeau** [comment] 2018-02-08 00:41
Hi Eric. I'm glad there is some interest for mapcomp!

It should be noted that mapcomp does not need deployment and that this is by design. Users simply clone or download the repository, put their data files in the right folder, and launch an analysis. If you make sure you have modules for bwa, samtools, R and the other dependencies, then your users will have no problem using mapcomp without you having to maintain modules for it.

I know this deviates from standard *NIX installation, but it is my opinionated (and potentially wrong) view that, in certain types of projects, proceeding like this makes doing multiple analyses easier, more reproducible, and more comparable. This has been my experience while having a group of a dozen or more users doing hundreds of RAD-Seq analyses in our group by using my stacks_workflow repository. Having a common stacks_workflow directory structure among projects has saved our group thousands of analysis and debugging hours. Using this approach, it has been easy, over the years, to jump from one user project to another without ever become lost because they are all similar. I am convinced that having a bunch of scripts in a folder added to the user PATH variable instead would have led to chaos and mighty headaches.

So, while I understand the desire to "deploy" mapcomp, it simply does not need to be deployed. Having the dependencies covered by your modules is enough.

~~The only way I would consider changing this approach would be to write the whole of mapcomp in Python3 and so essentially have only one script to deploy.~~ Actually, I'm not sure I would consider redoing mapcomp.

I'll be thinking about this some more but for now I think mapcomp is good to go as it is.

Thanks for your feedback!

**Comment by enormandeau** [comment] 2018-02-12 16:07
Closing but don't hesitate to add feedback.

**Closed as completed by enormandeau** 2018-02-12 16:07 UTC
